set(PACKAGE_VERSION "1.0.0")

if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
endif()

if(NOT PACKAGE_VERSION_COMPATIBLE)
  message(FATAL_ERROR "Package version is not compatible: ${PACKAGE_VERSION} < ${PACKAGE_FIND_VERSION}")
endif()
